/*  */
<template>
  <!-- eslint-disable max-len -->
  <!-- eslint-disable vue/no-parsing-error -->
  <v-app :theme="theme">
    <v-main>
      <v-container>
        <div class="d-flex color-picker-wrapper align-center mb-10">
          <h2>Pick your theme color</h2>
          <v-avatar
            class="cursor-pointer"
            @click="toggleTheme('myCustomLightTheme')"
            color="#eee"
            size="56"
          ></v-avatar>
          <v-avatar
            class="cursor-pointer"
            @click="toggleTheme('myCustomDarkTheme')"
            color="#000"
            size="56"
          ></v-avatar>
          <v-avatar
            class="cursor-pointer"
            @click="toggleTheme('myCustomTheme')"
            color="#167CF4"
            size="56"
          >
          </v-avatar>
          <v-avatar
            class="cursor-pointer"
            @click="toggleTheme('myCustomTheme2')"
            color="#0BA87C"
            size="56"
          >
          </v-avatar>
        </div>
      <v-container>
        <section>
          <h1 class="mb-5">Custom colors showcase</h1>
          <h2 class="mb-2">
            Vuetify generates custom colors on theme projects as css vars
          </h2>
          <h3 class="mb-2">
            here is an example of an added custom color on every theme and
            possible use cases
          </h3>
          <div class="bg-custom-color on-custom-color mb-2">
            If we name our color "custom-color" we can use then built in classes
            like "bg-custom-color" to get background of that color or class
            "on-custom-color" which will pick a right text color based on
            contrast
          </div>
          <div class="text-custom-color">class "text-custom-color"</div>
          <div class="custom-class">
            Here we are using custom class where we apply css variables
            generated by vuetify from the theme object
            I.E.(rgba(var(--v-theme-custom-color), 0.9);)
          </div>
        </section>
      </v-container>
      <h1 class="mt-10 mb-5 text-center">Default vuetify theming</h1>
      <v-card :loading="loading" class="mx-auto my-12" max-width="374">
        <v-progress-linear
          v-if="loading"
          class="position-absolute"
          style="z-index: 1"
          color="deep-purple"
          height="10"
          indeterminate
        ></v-progress-linear>

        <v-img
          height="250"
          src="https://cdn.vuetifyjs.com/images/cards/cooking.png"
          cover
        ></v-img>

        <v-card-header>
          <v-card-header-text>
            <v-card-title>Cafe Badilico</v-card-title>

            <v-card-subtitle>
              <span class="mr-1">Local Favorite</span>

              <v-icon
                color="error"
                icon="mdi-fire-circle"
                size="small"
              ></v-icon>
            </v-card-subtitle>
          </v-card-header-text>
        </v-card-header>

        <v-card-text>
          <v-row align="center" class="mx-0">
            <v-rating
              :model-value="4.5"
              color="amber"
              dense
              half-increments
              readonly
              size="14"
            ></v-rating>

            <div class="text-grey ms-4">4.5 (413)</div>
          </v-row>

          <div class="my-4 text-subtitle-1">$ • Italian, Cafe</div>

          <div>
            Small plates, salads & sandwiches - an intimate setting with 12
            indoor seats plus patio seating.
          </div>
        </v-card-text>

        <v-divider class="mx-4 mb-1"></v-divider>

        <v-card-title>Tonight's availability</v-card-title>

        <div class="px-4">
          <v-chip-group v-model="selection">
            <v-chip>5:30PM</v-chip>

            <v-chip>7:30PM</v-chip>

            <v-chip>8:00PM</v-chip>

            <v-chip>9:00PM</v-chip>
          </v-chip-group>
        </div>

        <v-card-actions>
          <v-btn color="deep-purple-lighten-2" text @click="reserve">
            Reserve
          </v-btn>
        </v-card-actions>
      </v-card>
      </v-container>
      <router-view />
    </v-main>
  </v-app>
</template>

<script lang="ts">
import { ref } from 'vue';
/* eslint-disable no-return-assign */
export default {
  name: 'App',
  setup() {
    const theme = ref('myCustomLightTheme');
    const loading = ref(false);
    const selection = ref(1);

    function toggleTheme(value: string) {
      theme.value = value;
    }

    function reserve() {
      loading.value = true;

      setTimeout(() => (loading.value = false), 2000);
    }

    return {
      theme,
      toggleTheme,
      loading,
      selection,
      reserve,
    };
  },
};
</script>

<style lang="scss" scoped>
.custom-class {
  /* background: rgb(var(--v-theme-custom-color)); */
  color: rgba(var(--v-theme-custom-color), 0.9);
}
.cursor-pointer {
  cursor: pointer;
}
.color-picker-wrapper {
  gap: 10px;
}
.background-grey {
  background-color: #fafafa;
}
</style>
